apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: pillguide-ingress
  namespace: pillguide
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: "20m"
    nginx.ingress.kubernetes.io/use-regex: "true"
    nginx.ingress.kubernetes.io/rewrite-target: /$2
spec:
  ingressClassName: nginx
  rules:
    - host: pillguide.site
      http:
        paths:
          - path: /api(/|$)(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: pillguide-service
                port:
                  number: 80